ori-edge/k8s_gateway

- charts/k8s-gateway/templates/configmap.yaml
- charts/k8s-gateway/values.yaml
Incorrectly reused value in Helm chart has been renamed
> Fixes ori-edge/k8s_gateway#8 (rename incorrectly reused "resources")

- charts/k8s-gateway/Chart.yaml
- charts/k8s-gateway/README.md
- charts/k8s-gateway/templates/deployment.yaml
- charts/k8s-gateway/templates/service.yaml
- charts/k8s-gateway/values.yaml
Support deploying as NodePort service on specific node
At the time I didn't know k8s_gateway only resolves type: LoadBalancer services and that only type: LoadBalancer get service status.loadbalancer.ip field populated. After deploying k8s_gateway I ended up deploying metallb and will likely go back to using type: LoadBalancer.
Also it turns out type: LoadBalancer was already working by default in k3s with https://github.com/k3s-io/klipper-lb.
But nonetheless this PR correctly adds support for nodePort that I'm currently using :+1:
> chart: Add nodeport and nodeSelector support

- charts/k8s-gateway/Chart.yaml
- charts/k8s-gateway/templates/service.yaml
The `loadBalancerIP` setting should be at the same level as
`type: LoadBalancer`, not in the per-port settings.
> charts: service: move loadBalancerIP from port to top level of spec

- kubernetes.go
- kubernetes_test.go
Where the following service declaration would be exposed as `nginx.default.example.com`, with this PR it would be exposed as `web.example.com` (assuming the configured zone is example.com).
```yaml
kind: Service
apiVersion: v1
metadata:
name: nginx
annotations:
coredns.io/hostname: web
spec:
type: LoadBalancer
ports:
- port: 80
selector:
app: nginx
```
> Add support for overriding the hostname with annotations

- README.md
- gateway.go
- kubernetes.go
- setup.go
This allows you to configure a path for a `kubeconfig` to communicate with an external Kubernetes cluster.
```
.:53 {
k8s_gateway example.org {
kubeconfig /config
}
}
```
Probably needs some tests, but works just fine.
Fixes #12
> Add support for external cluster with kubeconfig

- README.md
- gateway.go
- setup.go
This adds support for the `fallthrough` CoreDNS option which allows other plugins a chance to respond if `k8s_gateway` can't provide an answer.
Example use case:
```
.:53 {
errors
log
ready
k8s_gateway example.com {
fallthrough
}
forward . /etc/resolv.conf
cache 30
loop
reload
loadbalance
}
```
In this scenario if a valid Ingress or Service in the cluster does not match `example.com`, the request will be forwarded to the host's resolvers. In my case this is helpful because I run a split-brain DNS setup and if a record isn't defined locally in the cluster, I want to attempt to resolve it from my external DNS server as well (and only then ultimately return `NXDOMAIN` if it doesn't exist).
> Add fall through support

- .gitignore
- apex.go
- apex_dual_test.go
- apex_test.go
- gateway.go
- gateway_test.go
This PR allows to query the zone root domain and fall through if it doesn't match a resource.
**Tests needs to be adjusted after agreement on actual behaviour.**
Fixes #35
> Allow root zone queries and fall through

- charts/k8s-gateway/templates/configmap.yaml
- charts/k8s-gateway/values.yaml
Helm values.yaml secondary key did not match up with the readme, and the configmap was missing an entry for a secondary nameserver. Both have been fixed.
> Fixed missing secondary value from Helm chart

- README.md
Use raw uri instead of original github url in order to avoid the following error:
```
error: error parsing https://github.com/ori-edge/k8s_gateway/blob/master/examples/install-clusterwide.yml: error converting YAML to JSON: yaml: line 141: mapping values are not allowed in this context
```
> docs: fix kubectl apply url

- charts/k8s-gateway/Chart.yaml
- charts/k8s-gateway/templates/deployment.yaml
Remove extra right strip, fixing a YAML parsing error.
Before:
```
$ helm template ./k8s-gateway --set domain=my.domain --set priorityClassName="testing"
Error: YAML parse error on k8s-gateway/templates/deployment.yaml: error converting YAML to JSON: yaml: line 62: mapping values are not allowed in this context
```
After:
```
$ helm template ./k8s-gateway --set domain=my.domain --set priorityClassName="testing"
<correctly rendered YAML with no error>
```
I included a bump to the Helm chart version as part of this change set.
> Fix Helm Chart's priorityClass rendering

- .goreleaser.yml
Enable creating a freebsd binary on release (useful to deploy on opnsense or pfsense)
> feat: release binary for freebsd

- .github/dependabot.yml
Add [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to keep go dependencies and docker up to date. Relates to [dependencies auto-update](https://github.com/ori-edge/k8s_gateway/issues/91) issue.
> add go dependencies and docker auto-uptdate

- README.md
- kubernetes.go
This adds support for the Annotation currently used by External-DNS, `external-dns.alpha.kubernetes.io/hostname`,  for Service types. Since a lot of software out there has adopted external-dns as it's default supported means of external DNS resolution. This simplifies those integrations. 
Of note the support for TTL annotations, `external-dns.alpha.kubernetes.io/ttl`, was not added as k8s_gateway doesn't have support for Controller resolved TTLs overriding the default.
> Added support for External-DNS Annotations for Services

- .goreleaser.yml
- Makefile
Adding building for mips64 too which is used by EdgeRouter-4, EdgeRouter-12 for example from Ubiquiti.
> Build for mips64

- charts/k8s-gateway/templates/configmap.yaml
currently (tested in v0.3.3 and master) when an extraZonePlugins block is specified, `blockConfig` is indented using 2 spaces which breaks the yaml rendering of the configmap.
If I use this values file
```yaml
domain: test.lan
extraZonePlugins:
- name: hosts
configBlock: |
192.168.1.20 host0
192.168.1.21 host1
```
helm can't render the chart using `helm template -s templates/configmap.yaml -f VALUES k8s-gateway` and crashes with this error:
`Error: YAML parse error on k8s-gateway/templates/configmap.yaml: error converting YAML to JSON: yaml: line 23: could not find expected ':'`
Here is the output of the configmap when passing the flag `--debug`:
```yaml
data:
Corefile: |-
.:1053 {
k8s_gateway test.lan {
apex release-name-k8s-gateway.default
ttl 300
}
hosts {
192.168.1.20 host0 …
```
> fix chart indentation of extraZonePlugins

- .github/workflows/ci.yml
- Makefile
Follow up to https://github.com/ori-edge/k8s_gateway/pull/234
This increases `golangci-lint` timeout to 5 minutes as CI is not fast enough on an uncached run.
cc/ @networkop
> fix: Increase golangci-lint timeout

- README.md
- Tiltfile.nerdctl
- apex_dual_test.go
- examples/install-clusterwide.yml
- gateway.go
- gateway_test.go
- kubernetes.go
- kubernetes_test.go
- test/backend.yml
- test/cilium/dual-stack/crd-values.yaml
- test/cilium/helm-values.yaml
- test/cilium/single-stack/crd-values.yaml
- test/dual-stack/ingress-services.yml
- test/dual-stack/k8s-gateway-values.yaml
- test/dual-stack/service-annotation.yml
- test/gateway-api/crds.yml
- test/gateway-api/resources.yml
- test/gatewayclasses.yaml
- test/kind-with-registry.sh
- test/metallb-values.yaml
- test/nginxinc-kubernetes-ingress/values.yaml
- test/single-stack/ingress-services.yml
- test/single-stack/k8s-gateway-values.yaml
- test/single-stack/service-annotation.yml
- use experimental install crds, for tests
- add tests for tls and grpc
would close #237
> feat(gateway-api): Add initial support for tls and grpc routes

- charts/k8s-gateway/Chart.yaml
- charts/k8s-gateway/templates/service.yaml
- charts/k8s-gateway/values.yaml
In addition to annotations, for my use case involving `matchLabels` it would be helpful to be able to add additional labels to the Service. This PR adds a `service.labels` value to the Helm chart to allow custom labels. The implementation copies that of `service.annotations`.
> Helm chart: allow custom service labels

- .gitignore
- Makefile
- index.yaml
When attempting to update the chart index in #256, I noticed that `make helm-release` completely rebuilds the Helm index file and updates the timestamp of every release, including existing ones. It's pretty insignificant, but it makes for a larger diff on chart updates so I wondered whether there was a good solution.
It turns out this is a known limitation in Helm (https://github.com/helm/helm/issues/7363) but can be solved pretty easily by isolating the new chart when computing the updated index, and then merging the existing index.
For completeness I then updated the index with the correct, earliest timestamp for each version, based on the current digest. (A few versions had been updated in place over time.)
```bash
for digest in $(yq '.entries."k8s-gateway"[].digest' index.yaml); do …
```
> Avoid changing all chart timestamps when updating Helm index

- charts/k8s-gateway/Chart.yaml
- charts/k8s-gateway/README.md
- charts/k8s-gateway/templates/configmap.yaml
- charts/k8s-gateway/templates/deployment.yaml
- charts/k8s-gateway/templates/rbac.yaml
- charts/k8s-gateway/templates/service.yaml
- charts/k8s-gateway/templates/serviceaccount.yaml
- charts/k8s-gateway/values.yaml
Hello,
I need to add this feature to the current helm chart.
The customLabels value is used to add custom labels to all resources, so that they can be easily grouped with others and then retrieved using the selector label.
The toleration value is used to schedule pods on master nodes, for example.
The topologySpreadConstraints value is used to control how Pods are spread across your cluster.
The service.useTcp value is used to also enable tcp protocol on dns port.
Regards
> feature(add customLabels, tolerations, topologySpreadConstraints and service.useTcp values)

- README.md
I was reading the docs earlier and noticed a couple stale parts of the readme which must of come from some previous moves.
- Fix a link to the service annotations.
- Update local test path reference.
> README: Minor reference updates
